### PR TITLE
feat: fix for PipboyLightInvFix

### PR DESCRIPTION
**Pull request by rollingrock**
This is an address fix for the PipboyLightInvFix.     So far I have not encountered any new crashes but want to playtest some more in some different enviroments and equipment loadouts to see.

also had to make some updates to some files to compile with latest commonlib.    Let me know if I did any of these wrong and should change.

### CODE REVIEW

**Comment by alandtse** [comment]
Mind just doing a PR with just the changes to the address? Don't want to pollute the commit history with unrelated edits.

**Comment by rollingrock** [comment]
the other stuff was needed to compile with latest vs and latest commonlib.    i don't think i have anything in there that wasn't needed.

**Comment by alandtse** [comment]
Right but normally they should be separate PRs. I think I have a fix anyway at the old address. This may end up closed.

**Comment by alandtse** [comment]
Ok, I believe my fix should do what you were intending and also will be cross flat/vr. I removed some asm in the patch since you don't need to clobber that many bytes to install the write_branch.

**Pull request closed without merging**
